service: example-project-node

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    SALT: 10
    JWT_SECRET: 'pitangsecret' 
    JWT_EXPIRATION_TIME: '30m'
    MONGO_URL: mongodb://admin:Pit%40ng01@ds137498.mlab.com:37498/example-project

plugins:
  - serverless-offline

functions:
  app:
    handler: index.server
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
